### PR TITLE
Fixes#381:Wrong Status Bar Color in CircleOfTrust and SignUp Activity

### LINKED ISSUE #381: Wrong Status Bar Color in CircleOfTrust and SignUp Activity
Currently, the color of status bar in Circle Of Trust and Sign Up Activity is wrong as shown below.
whatsapp image 2017-02-15 at 2 24 33 pm
whatsapp image 2017-02-15 at 2 24 53 pm

Fix - Color should be changed to dark green color.
@sandarumk Can i work on this. Thanks

### PR DESCRIPTION
**Pull request by HimanshuS01**
Fixes #381 

**Fix**
Changing the Status Bar color in pre-Lollipop(5.0) is not possible by setting colorPrimaryDark as mention in this [Android Developers Blog.](https://android-developers.googleblog.com/2014/10/appcompat-v21-material-design-for-pre.html)

So I checked the version and change the **status bar color** programmatically in Trustees and SignUpActivity.java 

**ScreenShot**
untitled-1

@sandarumk Please review this PR.
Thank You

### CODE REVIEW

File: app/src/main/java/com/peacecorps/pcsa/circle_of_trust/Trustees.java [hunk 1]
```diff
@@ -59,6 +62,11 @@ protected void onCreate(Bundle savedInstanceState) {
 
         toolbar = (Toolbar)findViewById(R.id.toolbar_trustees);
         setSupportActionBar(toolbar);
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
+            getWindow().addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
+            getWindow().clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
+            getWindow().setStatusBarColor(ContextCompat.getColor(this, R.color.status_bar_color));
+        }
```
Comment (chamika) [inline app/src/main/java/com/peacecorps/pcsa/circle_of_trust/Trustees.java]: The same code duplicates in two activities. Can you create a method in a util class and move the code segment to there. Then refer the newly created method in both places.

Comment (HimanshuS01) [reply app/src/main/java/com/peacecorps/pcsa/circle_of_trust/Trustees.java]: Sure @chamika. I will do the same..  
Thank you :)

**Comment by HimanshuS01** [comment]
@chamika @sandarumk I have moved all the redundant code to util class. 
Please review this PR.
Thank You

File: app/src/main/java/com/peacecorps/pcsa/StatusBarColorUtil.java [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+    private static Context context;
+    private static Window window;
+
+    public StatusBarColorUtil(Context context, Window window) {
+        this.context = context;
+        this.window = window;
+    }
+
+    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
+    public void changeStatusBarColor() {
```
Comment (chamika) [inline app/src/main/java/com/peacecorps/pcsa/StatusBarColorUtil.java]: Make this method a public static one. This is kind of a Util class practice. You do not create an instance of Util classes. 
Ex: 
public static void changeStatusBarColor(Context context, Window window){
    if (VERSION CHECK) { // move version check to here since it is common to all activities
        //do status bar update
    }
}

Then you can simply call this method similar to below
StatusBarColorUtil.changeStatusBarColor(this,getWindow());

Comment (HimanshuS01) [reply app/src/main/java/com/peacecorps/pcsa/StatusBarColorUtil.java]: sure @chamika .I will do the same and Thanks for reviewing this PR.
:)

**Comment by HimanshuS01** [comment]
@chamika changes done. Please have a look now :)
thanks

**Comment by chamika** [comment]
+1
